### ISSUE TITLE
Uncaught TypeError: value is out of bounds

### ISSUE THREAD

**Issue by SqrTT** [thejoshwolfe/yazl#23]
Hi,
We are [faced](https://github.com/SqrTT/Bart/issues/2) with issue that throws this error.

```
At buffer.js:825

TypeError: value is out of bounds
    at checkInt (buffer.js:825:11)
    at Buffer.writeUInt16LE (buffer.js:883:5)
    at getEndOfCentralDirectoryRecord (/Users/adamclason/.atom/packages/Bart/node_modules/yazl/index.js:220:10)
    at pumpEntries (/Users/adamclason/.atom/packages/Bart/node_modules/yazl/index.js:185:33)
    at ByteCounter.<anonymous> (/Users/adamclason/.atom/packages/Bart/node_modules/yazl/index.js:142:5)
    at emitNone (events.js:72:20)
    at ByteCounter.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

Is there some way to increase count of files?

PS. Thanks for module. :)

**Comment by SqrTT** [comment]
It's sad but look like this is limitation of zip format... so closing issue.

**Comment by thejoshwolfe** [comment]
what you're looking for is #6: ZIP64 support. I have plans to make this happen, but it's a bit complicated and, I could use some external motivation :)

I'll see about implementing something useful for you soon.

**Comment by thejoshwolfe** [comment]
yazl 2.4.0 is published, which includes ZIP64 support. This issue should be solved if you update to the latest yazl. please let me know if you run into any issues.
